/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/DzU4mQwRctO
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Image from "next/image";

import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

export function CurrencyConverter() {
  return (
    <div className="flexitems-center">
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button
            className="w-24 justify-between pl-2 text-left"
            variant="outline"
          >
            AUD
            <ChevronDownIcon className="ml-auto h-4 w-4" />
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent>
          <DropdownMenuGroup>
            <DropdownMenuItem className="cursor-pointer">
              <Image
                alt="EURO"
                width={30}
                height={30}
                className="mr-4"
                src={"/MAB/Icons/flag.png"}
              />
              USD
            </DropdownMenuItem>
            <DropdownMenuItem className="cursor-pointer">
              <Image
                alt="EURO"
                width={30}
                className="mr-4"
                height={30}
                src={"/MAB/Icons/euro.png"}
              />
              EUR
            </DropdownMenuItem>
            <DropdownMenuItem className="cursor-pointer">
              {" "}
              <Image
                alt="EURO"
                width={30}
                height={30}
                className="mr-4"
                src={"/MAB/Icons/australia.png"}
              />
              AUD
            </DropdownMenuItem>
            <DropdownMenuItem className="cursor-pointer">
              {" "}
              <Image
                alt="EURO"
                width={30}
                height={30}
                className="mr-4"
                src={"/MAB/Icons/canada.png"}
              />
              CAD
            </DropdownMenuItem>
            <DropdownMenuItem className="cursor-pointer">
              {" "}
              <Image
                alt="EURO"
                width={30}
                height={30}
                className="mr-4"
                src={"/MAB/Icons/united-kingdom.png"}
              />
              GBP
            </DropdownMenuItem>
            <DropdownMenuItem className="cursor-pointer">
              {" "}
              <Image
                className="mr-4"
                alt="EURO"
                width={30}
                height={30}
                src={"/MAB/Icons/united-arab-emirates.png"}
              />
              AED
            </DropdownMenuItem>
          </DropdownMenuGroup>
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
  );
}

function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  );
}
